public enum CharacterPrefabNames
{
    Cute_Bird_00c,
    Cute_Bird_42,
    Cute_Bird_43,
    Cute_Bird_44,
    Cute_Bird_45,
    Cute_Bird_46,
    Cute_Bird_47,
    Cute_Bird_48,
    Cute_Bird_49,
    Cute_Bird_50,
    Cute_Bird_51,
    Cute_Bird_52,
    Cute_Bird_53,
    Cute_Bird_54,
    Cute_Bird_55,
    Cute_Bird_56,
    Cute_Bird_57,
    Cute_Bird_58,
    Cute_Bird_59,
    Cute_Bird_60
}